get_news_articles_job:
  cron: "0 */6 * * *" # Run every 6 hours
  class: Schedule::GetNewsArticlesJob
  queue: schedule
  schedule_type: default
  
send_events_notifications_job:
  cron: "*/10 * * * *" # Run every 10th minutes
  class: Schedule::SendEventsNotificationsJob
  queue: schedule
  schedule_type: default
  priority: 1
  
generate_sitemap_job:
  cron: "0 4 * * *" # Run at 4 AM everyday
  class: Schedule::GenerateSitemapJob
  queue: schedule
  schedule_type: default
